# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rails', '~> 7.0.8'

gem 'bootsnap', require: false
gem 'cssbundling-rails', '~> 1.1'
gem 'puma', '~> 6.3'
gem 'sprockets-rails'

gem 'lookbook'
gem 'optics_view_components', path: '../'

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
end

group :development do
  gem 'web-console'
end
